language: node_js
os:
  - osx
  - linux
node_js: 8

before_install:
  - |
    if [ $TRAVIS_OS_NAME == "linux" ]; then
        export DISPLAY=:10;
        set -e
        /usr/bin/Xvfb :10 -ac >> /tmp/Xvfb.out 2>&1 &
        disown -ar
    fi

install:
  - yarn

script:
  - yarn compile
  - yarn test

cache: yarn
